language: go

before_install:
  # Setup dependency management tool
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip
